/* GENERATED by scratchpad/photos/process.mjs — do not edit by hand.
   46 photographs from the school, exported as responsive WebP
   into public/photos/. Every entry carries its own alt text and caption. */

export type PhotoCategory =
  | "staff"
  | "campus"
  | "boarding"
  | "faith"
  | "earlyyears"
  | "academics"
  | "sport"
  | "music"
  | "community"
  | "trips"
  | "life";

export type Photo = {
  slug: string;
  cat: PhotoCategory;
  alt: string;
  caption: string;
  /** object-position hint for tiles cropped tighter than the source. */
  focus: "attention" | "north";
  width: number;
  height: number;
  widths: number[];
  /** 20px WebP, inlined — the blur shown while the real file loads. */
  blur: string;
};

export const photos: Photo[] = [
  {
    "slug": "staff-outside-block",
    "cat": "staff",
    "alt": "The teaching staff of St Stephen's standing together outside the long sky-blue classroom block",
    "caption": "Twenty-six teachers, one staffroom",
    "focus": "north",
    "width": 1280,
    "height": 960,
    "widths": [
      480,
      800,
      1200,
      1280
    ],
    "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADQAwCdASoUAA8APwlurk+rpiQiMAgBcCEJYgCsACHYLsGbW6tkLwAA/nkw4NTTvp6dyGTGEZbciYh1xput1K7DmdHkxLMXpRlTFHCfDns1F+o+zb4AYi1BP/DG3iHpKmrVs1DAZzoDOVN8RsberSKyUFD1+pF6v03GHTl+AAA="
  },
  {
    "slug": "staff-parade",
    "cat": "staff",
    "alt": "Members of staff lined up along the classroom veranda before the school day",
    "caption": "Before the bell",
    "focus": "north",
    "width": 1600,
    "height": 720,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQAwCdASoUAAkAPwlur0+rpiQiMAgBcCEJYwC7ABSKyXkclSbAAP68dNY1MqZCbAaMqcEFUGiAZrC14Pi8pUZbAgnPMnk9hlM985SvLijX44y6KtU1/MfLsl5wsJAavWNxA1QAAAA="
  },
  {
    "slug": "classroom-lesson",
    "cat": "campus",
    "alt": "A teacher standing over young learners working at a desk inside a classroom",
    "caption": "Inside a classroom",
    "focus": "attention",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAAAwBQCdASoUABsAPwlurU+rpiQiMBgMAXAhCWMApxQQKxcvcafvG8fnNytV2YWQldJAAADKs03zrQVFkyjO3eko85fNbQMyEDeDdrxr4g93hPAt5cRKXdl6j3XjJFgIiX3ZXOJp/4iGHOrwEdp6+dx7sSWEmie8ndYGi7qxXBKHjvgHTGD7YuBfh+KS4I8qNAA="
  },
  {
    "slug": "school-grounds",
    "cat": "campus",
    "alt": "A speaker addressing the school beside the flowerbeds, with the sky-blue buildings behind",
    "caption": "The compound at Kimaeti",
    "focus": "attention",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRtwAAABXRUJQVlA4INAAAABwBQCdASoUABsAPwl2tVKrpyUiqAqpcCEJaACpJ47lywgkwbz4avIacC88l8PQ/KwtLc8AAP0hIDy+43xDs4LnonxZI7ZJD8G7vY6yGSQJSyLsnEOYuoQijWOIBqq8A0UQnoBK/O6ehiMOgLB8S7i+5D0N5bGdp4+YEZgxcVmY/UYiOTqm7XA3GsrveW0uCFCbQC1aJqNnOcSh2qm9JUculhstaxCJ73+XgnzcKP3L23K+a/FYUHEk0I5K+hO60LRkmjEz2ymttf5W6ebcjAAA"
  },
  {
    "slug": "water-tank",
    "cat": "campus",
    "alt": "Learners and workmen laying the concrete rings of the school's water tank",
    "caption": "Building the school's water tank",
    "focus": "attention",
    "width": 1600,
    "height": 1200,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwAwCdASoUAA8APwlurk+rpiQiMAgBcCEJZgCdIL/BXRFbEIi0YAD6gA0CQ6prZbb12ffQ7nv783sO5n04PrLjhmDRyMnTox7bb5CPsoohI3UNy3x/xFv2wzsiVHxsRsENRVv3bcJXJeh59oYKgoPLdkCKAHVNgCyAAA=="
  },
  {
    "slug": "tank-rings",
    "cat": "campus",
    "alt": "Staff and learners easing a concrete ring into the ground during the water project",
    "caption": "The water project, ring by ring",
    "focus": "attention",
    "width": 1280,
    "height": 720,
    "widths": [
      480,
      800,
      1200,
      1280
    ],
    "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACQBACdASoUAAsAPwlur0+rpiQiMAgBcCEJbACdMoMjmJAA8aybWtUfvZRBPgAA4VGHIRBNfjNAhNkrBBqMp6+FFLI7hB7XcoWXrjL6jKIYoQhDIbPt0L6pS7+ADwcYrcaMtZl4/UsfniMibCmSkcpYLu+ysGEYW+x+L8k4OIPIAA=="
  },
  {
    "slug": "dining-hall",
    "cat": "boarding",
    "alt": "Boarders seated along a long dining table with plates and water bottles",
    "caption": "Supper in the dining hall",
    "focus": "attention",
    "width": 1600,
    "height": 1200,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAwCdASoUAA8APwlwr0+rpiQiMAgBcCEJZQAASVsOInUMoa0sAAD95tzTG40oWUN6+1/7dx/SIWqhFeCjfPNw36KFHnUbeaVflaMMHjsgTExy4H5W/LP9+9PMI78zAAA="
  },
  {
    "slug": "dining-juniors",
    "cat": "boarding",
    "alt": "Junior school boarders eating together at the dining tables",
    "caption": "157 boarders eat here every day",
    "focus": "attention",
    "width": 1600,
    "height": 1200,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwAwCdASoUAA8APwlurk+rpiQiMAgBcCEJZQDE2BO4AxSJYEkjAAD+mRxdQ3gB1NWnfDPhrF/AIAdvtnoXTyRgG3LfPcMfs1PVtNa5vLCmo2Jv3U1mpXvVS89kfWq3cnAs8irqt8yF5UoAAAA="
  },
  {
    "slug": "mass-outdoors",
    "cat": "faith",
    "alt": "A priest in green vestments at a lectern in the school compound, the whole school standing around him",
    "caption": "Open-air Mass in the compound",
    "focus": "attention",
    "width": 1600,
    "height": 900,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwAwCdASoUAAsAPwlur0+rpiQiMAgBcCEJQBOiP/wGhwTBwXXKwAD+kbcZdkZfdCxFBnwOTTrnlIcN3DrekP9y7gP4B/Ge4pWerfWAzvpi6a9syG8pg1ilBxP3noEk13sD2cP3CgeXyOu7H5FGFAAA"
  },
  {
    "slug": "mass-lectern",
    "cat": "faith",
    "alt": "Learners standing with hands joined in prayer around the lectern at an open-air Mass",
    "caption": "The praying half of the motto",
    "focus": "attention",
    "width": 1600,
    "height": 900,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACQBACdASoUAAsAPwlwr1ArpqQisAgBcCEJZACdMoADEamHTz/yxYfQRWcnmwAA/LQi0NbHb/uXWI8ujVjRpA2aWfG5tQc+yw9AhSfyL037ddpLw2O7pl4UQOihz4xUP4rC+yXk+VhUtoC8TpwtIIAA"
  },
  {
    "slug": "early-years-nutrition",
    "cat": "earlyyears",
    "alt": "Early-years children in yellow t-shirts behind a table of vegetables, fish and chapati, with hand-drawn charts naming each food",
    "caption": "Food groups, Early Years",
    "focus": "attention",
    "width": 1600,
    "height": 1204,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAQBACdASoUAA8APwlurk+rpiQiMAgBcCEJagCdMoQP6Am4ruxSLSWOYAD+TMAe7Q69Q8ZfEA5z/4J6IbPeBf88CkKN+yDQ6WNLpDu0rMDtYs2KQdS1wD7/J2hpf17MpnUyPoTWfRm5Kwlb69/1XkQ6PEhr1CWAgRJCFo+6JkMdQ1nSuSF8OAAA"
  },
  {
    "slug": "early-years-desks",
    "cat": "earlyyears",
    "alt": "Small children in yellow t-shirts sitting at a desk at the science fair",
    "caption": "Playgroup, PP1 and PP2",
    "focus": "attention",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAACQBQCdASoUABsAPwl4slMrpySiqAqpcCEJbACdMoM1OG9JOFNcazjFOhtnq/BZ4ox7qz+/AAD+6UOduHarUTOSM3hFhIbu/94Gd3pZfCzti20/2N18B5nbR2t8hMex9guCEnp38AWWGFQzo7zd5rGJWU4ThJTookko8XXGDoLDKIGJEwlZMaJlhrCLdY7S4IX3E/2cJ9m4PAq4JYd98IDH5VzXFNG53tNAPlJVIi5KI1EV2RrJZIoKDrHkMS+0K22ZavwahLxwQTCpqSAAAA=="
  },
  {
    "slug": "early-years-presenting",
    "cat": "earlyyears",
    "alt": "A boy in a yellow t-shirt standing beside his own project chart, waiting to explain it",
    "caption": "His first time presenting",
    "focus": "north",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAACQBQCdASoUABsAPwlyslIrpqSisBgIAXAhCWoAnTKDOgAaV07t7oHCm1eSy9F8lLgkhe+2AADNT3FX3b19V6dGMffxqCcvLIW08JBaLMe7O35Ev3uWb/qzgi6KTrne3ZQzzEUyPXXnrt+iGn5zqtCnV9d73vT3qspM9lK9cFoL+4sCQ+exyoCdi5Z+qARqjMS+R+jrVCVaiayaoNbkYr5qcRBRjHqDri4V63FNKVzwg1E8oK+c9TaDQD6G+qmpmbiSAAAA"
  },
  {
    "slug": "gases-balloons",
    "cat": "earlyyears",
    "alt": "Three small boys holding balloons beside a chart reading: gases do not have fixed shape, they take the shape of the balloon",
    "caption": "“They take the shape of the balloon”",
    "focus": "north",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAACQBQCdASoUABsAPwl2slGrpySisBgIAXAhCWwAnTlBVbW/ANhwZrHZOoJfzaZUZlsaczTDAAD8ZcCcO+8cGQ7p0Ad0aTzS6JqbMIksBfVxhqunGXfMw7v0VlXe/+00ay4seTZMLrSiXA5keXn0DgZepJBfBTSKUeqgUgDPMEAsNtjyaFqjIgKe3x001OcnuGp30CU7e6O8A8gpT8zerAoJD6WhhgAA"
  },
  {
    "slug": "science-bottles",
    "cat": "academics",
    "alt": "Learners pouring liquid between bottles and jars at an outdoor bench, beside a chart headed Investigating Osmosis",
    "caption": "Investigating osmosis",
    "focus": "attention",
    "width": 1600,
    "height": 1204,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwAwCdASoUAA8APwlurk+rpiQiMAgBcCEJbACdABMXODlDgmV1QAD+GVKkFMhwcL+2U8W20RSnHkFCWDxpsTySR9uMtvzwROEve0c74H/UMrj7YFZ7JhD2iSHcN/BwcjtIhUWfwvLokIB5/RAfj+SFUebzvjlfmF4+pugLeZLEvg2sRpEAAAAA"
  },
  {
    "slug": "lab-coats",
    "cat": "academics",
    "alt": "Learners in white lab coats demonstrating their apparatus for softening hard water",
    "caption": "Softening hard water",
    "focus": "north",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRtwAAABXRUJQVlA4INAAAAAQBQCdASoUABsAPwlurk+rpiQiMAgBcCEJagCsMoACf1z/XNJnURmRpti5ujUnXj7QAP6XeetZ80sOPjU4LPVqab1OIOWJtWMAi4bibnD62PX6Ln5BzYNUsA3KArUHgRZBleJmq6go7E2aiU6s52T4DdnAdjusQupA8QCLdIUawKK+6LDkEY5W5GlWXm9giW60J4/y7HifhLW8W5RAzlaEutvAj9kkeLCanSBaGC/1wfy2xd2CD7p+sLeKuGVHnkoPAM/eLkkP77mUnx0yhQAA"
  },
  {
    "slug": "conduction-liquid",
    "cat": "academics",
    "alt": "Pupils presenting a chart headed Conduction in Liquid outside a classroom",
    "caption": "Conduction in liquids",
    "focus": "north",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAAAQBQCdASoUABsAPwl0slGrpqSisBgIAXAhCWYArCDQQKqZfFMaS/vazD9voruulUwAAP3bhoy+Cifkps2qIe2viQRDEr+urQl4CkDECq0ldtpmDK6K9D+uJ2dizrYeziKgcrdwVasO8pW4Naz/qc04wjNyk9YvV+bHfbNcepx50lnQikO+JMlSk67jLfoDUtaUD4bGSTEOss1NH4N6k9479fUjcHctm65MHVGFYI4ZHpdvEEKS5tAUKLbWjgAA"
  },
  {
    "slug": "project-chart",
    "cat": "academics",
    "alt": "Two learners at their table with a chart showing the arrangement of particles in solids, liquids and gases",
    "caption": "The arrangement of particles",
    "focus": "north",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAACwBQCdASoUABsAPwl4s1MrpySiqAqpcCEJaAC/WQCJ/gFKxdAA7t4OMpfNaCE6SPj+40yuQAAA/F4DUPhci8Mc64v9XOoNuivhOLJXm9aXiEFtMxoqab1s63Nu4i/CzPikrDW4Z0d3h8U5dBpjEbgZ2WwnFrrAFjBQlG4hcx/Y081+r4KMb/Ih5+fspy2GqMBIjSFc9MIe5cC4KAJDWbShTP2PbO0++pvbtRd5XK1EwospQqXoNg5oVNDL0I+Q+p0X2kJfH031blksgAA="
  },
  {
    "slug": "girls-presenting",
    "cat": "academics",
    "alt": "Girls in blue check dresses presenting their model under the fair tent",
    "caption": "Presenting under the tents",
    "focus": "north",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAABQBQCdASoUABsAPwlurk+rpiQiMAgBcCEJQBadBHmy7TTq1SY05/wm8id5rGvDODPYFQAA/q9v3rbaTtkLulJn5LK7ZpfCWFQmsPn0tgDtkxgZaia6FYYJFwQHbKWZPBmCbaAllOJalZdGWbUAJXWwp1rAyeiCYLP6j0dvC6kg5jAQAioAVy5eKYMDujwi7KhsMo2ChD3/44R9ZqdV+8Y0Yo37mfXeN29wuq1GImTwLYIVwIuffDC+hfStLY+k4phl2tMwfMAAAA=="
  },
  {
    "slug": "phototropism",
    "cat": "academics",
    "alt": "Learners standing beside a chart headed: plants grow towards the source of light",
    "caption": "Plants grow towards the light",
    "focus": "north",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAACQBQCdASoUABsAPwl4r1OrpyOiqAqpcCEJZgC2+oMsd+yhK7e0qWCg22qf4+pOm0hU4tLwAADyYq6MEfpKSVgb88nuyvzyx4bu/IxKWK7PolKtMRqxY/opwkMFGZIuCVwKUZkPtPatdrpLCExzOAOVvwYEOYFlJuQpd7fgnY1+yV409dprI80KC7KfA8p49M+OrGZ8vkIMrr4j3NA5ppjLKmCsZLbVukxE7rqxDBOZ45P9fnzDbLuKqou7VDqxQHm2AAAA"
  },
  {
    "slug": "young-exhibitors",
    "cat": "academics",
    "alt": "Young learners behind their exhibit on conduction in solids, under the fair tent",
    "caption": "Conduction in solids",
    "focus": "north",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAACQBQCdASoUABsAPwlurlArpiQisBgMAXAhCWQAnTKDNtBxyEAuG2UxRmocwS1ALHPFZovbAAD+8c6x2XvcgWxu75NERnJ6tizIEQKPKw747wP65/bQ54QtjT3P1hmTEtSXL5GPOJ+D55q7ofKjGY/FN6HsMkohBWZVmT/bZZYng4ejlFa4z9Hr6+w+WeJnVi3ZImc8S1VTTDnXPE+vxBJ/swljgAzoJ7DHlrk7oxKURfk6BIPFFzoAAAA="
  },
  {
    "slug": "oxygen-model",
    "cat": "academics",
    "alt": "Learners seated behind a hand-drawn model of the oxygen atom built from locally available materials",
    "caption": "Modelling the oxygen atom",
    "focus": "north",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRvwAAABXRUJQVlA4IPAAAAAwBgCdASoUABsAPwl6tVSrpySjKAgBcCEJbADFCoPINd3qu29mAWEHCbYWn3DuA0X7sGMs4r888acAAP35yMCH+OQYpQy77pA/0Ux+yzDnAUA3zVBb1obPPSjpcruFhuVbUC4rmGNIRPULYVb+G8QFW2kCWlqW9X6JljYyZMIWym1+Jbb5ACgOea0FKhG/eDjSIWSQSd+64aY/6QnF95A7v4Ra5jdWSfuzuIoF3GVoaN2+XOfuisOq3uNqYB7qqGKcgjRZkXO4r/nzQkSBKmcFJ0z6fRy6xWE8P+P7yL3oR8UhRQzJmVX/t0pfrdoAAAA="
  },
  {
    "slug": "explaining-to-judge",
    "cat": "academics",
    "alt": "Two boys explaining their project to a teacher judging the science fair",
    "caption": "Making the case to the judge",
    "focus": "north",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAABwBQCdASoUABsAPwlwrk+rpqQiMAgBcCEJbACdL0iBTlxAn62EMRbrO4hTXCbgTncwIdQAAPn1wPjy9f/MCtfFAfGTg+4ivW+8BDIHzY+vW2BW2+tbB0QrMLlkSzpY8jBtuzoA6c9j0btv/mFCTrzDqbmady92rZv4bua2hHawLU3Y+XaGl232gNpGHODYUHtVwxduEDsH3DzUx2zhGqujjFyY7+Oh3T7amdO9uw1hP0xsy6FMnQks8AAAAA=="
  },
  {
    "slug": "fair-stand",
    "cat": "academics",
    "alt": "Learners at exhibition stand 114, a teacher in a white coat standing behind them",
    "caption": "Stand 114",
    "focus": "north",
    "width": 1204,
    "height": 1600,
    "widths": [
      480,
      800,
      1200,
      1204
    ],
    "blur": "data:image/webp;base64,UklGRu4AAABXRUJQVlA4IOIAAADQBQCdASoUABsAPwluslIrpaSisBgIAXAhCWwAuzKDIdQUfyDGsUU8lMuBSzdnY4byIf0BsxBgAPVpNKO8VOy5409hhEqV4urLveNjy3qHeiSHoSDomLXkul4TaXk87rAquye/XwyGTIxJ9PFUPWI8oB2+LjQCgcPMdCMfnh1+JEKYwErvI1AFYt/22Cz0fSyOwRfKPug0+Nj7sRuQmpvWyIdHDoXxQeDG36ZfODjnJcsKryNA4pYQnvrJX59l356K5PCoOoJLp+N1AG5z/XySO1gJEoHPz6d7EgL2fWD/UqAA"
  },
  {
    "slug": "football-team",
    "cat": "sport",
    "alt": "The school football team in yellow-green kit posing with the ball on the pitch",
    "caption": "The school team",
    "focus": "attention",
    "width": 1600,
    "height": 720,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwAwCdASoUAAkAPwlur1ArpiQisAgBcCEJYwCdAB04ZkLpneAA/nhWg+dPIUwg7mvuFO7keH1IVs2Y59tfaTcqeJOl16vkNq4BMJVouTn7smIX6hGZTrHjhHq+m6AA"
  },
  {
    "slug": "football-squad",
    "cat": "sport",
    "alt": "Footballers in yellow-green strip lined up before kick-off",
    "caption": "Before kick-off",
    "focus": "attention",
    "width": 1600,
    "height": 720,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQAwCdASoUAAkAPwlur0+rpiQiMAgBcCEJQBadBAqI9pfSurjAAP1Mb6Hml0s7Wa2se5PhPO4fSAgvT5g9rz1VHed9HVhJbJfLAO6TYswjjspWmTvFc7dMwAA="
  },
  {
    "slug": "cultural-troupe",
    "cat": "music",
    "alt": "The cultural dance troupe in matching blue patterned outfits and red headbands",
    "caption": "Our cultural dance troupe",
    "focus": "attention",
    "width": 1280,
    "height": 960,
    "widths": [
      480,
      800,
      1200,
      1280
    ],
    "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADwAwCdASoUAA8APwlur0+rpiQiMAgBcCEJQBadAl7falfVbVyqtPDgAP3bzR+hNsc8MXj6ARAGA8m1qUzsYQ+ggwQARyg92/ZiqggKv/cNmhpYum5k9OCcK1ugKFheKXntmRD5d0KJ5x0brjz3lp4DG7DvBrXw7Q1rgSQTdQoNCDqAAAA="
  },
  {
    "slug": "shamba-work",
    "cat": "community",
    "alt": "Learners standing on the freshly planted school shamba",
    "caption": "Work as well as prayer",
    "focus": "attention",
    "width": 1600,
    "height": 1200,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoUAA8APwlur0+rpiQiMAgBcCEJZACw7BT8eE5BHX4AF8HmAAD9032tx+VqOosA68jlx7ZS28Uo2GmlRJxOmqovI5q30lxcUVoNCruoE+3uEToFnkdV13siXLD7OAhUyMRF1WAAAAA="
  },
  {
    "slug": "farm-plot",
    "cat": "community",
    "alt": "Pupils in sky-blue t-shirts on the school farm plot, the seedlings just coming up",
    "caption": "The school shamba",
    "focus": "attention",
    "width": 1600,
    "height": 1200,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQBACdASoUAA8APwlur0+rpiQiMAgBcCEJbACdAB0/RACfhdYtoPji9AD+XxqtuPNc99JlN5o/viMMBH4QMcSJXx4ugGRO8F4DMgFGe66KXYwXgeGumzo78yIrQUGXZf6io2HV9AA="
  },
  {
    "slug": "learners-on-the-field",
    "cat": "life",
    "alt": "Junior school learners in sky-blue shirts and maroon ties standing together on the grass",
    "caption": "Junior school, Grade 7 to 9",
    "focus": "attention",
    "width": 1600,
    "height": 1200,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoUAA8APwlwr1ArpqQisAgBcCEJYwCdEf/gKId+0AJa0UqeCADcrDaqtx7npTPMHZmzuAOOcPrYmfE43eWdEhnD2GzC+AjP8MCtcoNjiNa85vEC2I4z9QGVHTHT3K+UOR9OljdgAAA="
  },
  {
    "slug": "headteacher-and-pupils",
    "cat": "life",
    "alt": "A member of staff among a crowd of learners in the compound, the classroom block behind",
    "caption": "Known by name",
    "focus": "attention",
    "width": 1600,
    "height": 1200,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBACdASoUAA8APwlurk+rpiQiMAgBcCEJZAC7ABuV7h3WyEd+dd8M5QAA/rX+O2zt/T5c0gxAuQZc+LYsrRugJW4FVM82NW1jDgI6u9g+EwPRBP4idzUJTJniSAPBZ0P4av3kZb0k5NoE9CGDBHOHJMIvE0muEnzr/0YAAAA="
  },
  {
    "slug": "pupils-maroon-jumpers",
    "cat": "life",
    "alt": "A crowd of primary learners in maroon jumpers smiling at the camera",
    "caption": "Between lessons",
    "focus": "attention",
    "width": 1600,
    "height": 1200,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQAwCdASoUAA8APwlur0+rpiQiMAgBcCEJYgC7ACH+uPce1UsVXuAA/dukO8Cpt4KuWNQLLZFZeTseq3BXhkXFkHTHo9KTSj5vJ0Y0ga+DBto1wYP+2yWAu0x51y7jOXmwHLsG5ulwFz6OFiP0097Rbv02GzM+/ZtBRQzHbU0mKrEB/QU7m5kzAAA="
  },
  {
    "slug": "pupils-under-trees",
    "cat": "life",
    "alt": "Learners in maroon jumpers gathered under the trees at the edge of the compound",
    "caption": "Under the trees",
    "focus": "attention",
    "width": 1600,
    "height": 1200,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAQBACdASoUAA8APwlurk+rpiQiMAgBcCEJZgC7AYxihV7KdCz6P9MM4AD+s7wOznErLtHLjlH6RbHqjLNCu2fmSPQeYu7ToUlrUnatxV3t4kwvKZf9wFpVQS3aVCqHcU16EgqnancqbzSA0fGt8nfqVDzzjNYbajmPl5Tl/t8+zt1RdoBE01ziOLjHvIWh+U7n6nkMLviuAAAA"
  },
  {
    "slug": "festival-troupe",
    "cat": "music",
    "alt": "The school's dance troupe in pink skirts and white tops, lined up at a music festival venue",
    "caption": "At the music festival",
    "focus": "attention",
    "width": 1040,
    "height": 780,
    "widths": [
      480,
      800,
      1040
    ],
    "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAwBACdASoUAA8APwlurk+rpiQiMAgBcCEJbAC06CL3KgzgC9WmQAVPjeAA/scnExMaLEjDR7cgWZqaKifnf8Bk7+QZWO/Xp5s6XQxfssSpeTqQcemH0IWvfHl7fHbthf/i6iMbyLRV+BZSmci9TMz6EYsklE/1hTUGCJFWISYNLy8FOf8oyBjIKXkblAAA"
  },
  {
    "slug": "troupe-close",
    "cat": "music",
    "alt": "Members of the dance troupe with their arms round each other, laughing, before going on",
    "caption": "Waiting to go on",
    "focus": "attention",
    "width": 1040,
    "height": 780,
    "widths": [
      480,
      800,
      1040
    ],
    "blur": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAwBACdASoUAA8APwlur0+rpiQiMAgBcCEJbACdAYv+5aujJZ8X4ogWD4AA/kfI24PH3tx5rMB8RI6vbQDCtrgMu5h7T9KWe6o1p7qMRpIn1/8O2+GS/Japw3CHHSD7yq9RIZ7q9HHCyOyAeWhSRJB0nP3m6E4Ccvhzc3KMSJasmLXPjXipghEXT47JH4l535Zjp+e0pSYP7XsyAAA="
  },
  {
    "slug": "cultural-dancers",
    "cat": "music",
    "alt": "A large cultural dance group in matching patterned kit and red caps, holding sticks, seated and standing for a group photograph",
    "caption": "The cultural dance group",
    "focus": "attention",
    "width": 1040,
    "height": 780,
    "widths": [
      480,
      800,
      1040
    ],
    "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAwBACdASoUAA8APwlur0+rpiQiMAgBcCEJQBdj+DE/wHyzUINsIc9mL1gA/ud9HR6V+u9+Vu6JrWxE9q0jkLBE4fp8kRSSEMpnRbWkUuIa5S4Or+xTzvJWapyEapmXnmtQu9RyK4UJuxVcVcy6HEiQVqjHdheXxCFmvnBSHxIGsopHwirQJhEQAAA="
  },
  {
    "slug": "troupe-art-room",
    "cat": "music",
    "alt": "Dancers in pink and their teacher outside the door marked Art Room",
    "caption": "Outside the art room",
    "focus": "attention",
    "width": 1040,
    "height": 780,
    "widths": [
      480,
      800,
      1040
    ],
    "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAwBACdASoUAA8APwlurk+rpiQiMAgBcCEJbACdMoR4GBzcXJIVzzMpO/AA+jjjdzd6IFmVimrZGxnHAKpanVaca3zYOndvo27mnc6kNBxvDjbLOLcEHhw/cWa4xHYUVm19PXsYfivNdkSsGcCnZ/yTrV0vG+Ydcr8roVUKHTuSGAAA"
  },
  {
    "slug": "festival-travel",
    "cat": "music",
    "alt": "The whole contingent photographed on the grass beside the bus, a keyboard on the ground in front of them",
    "caption": "Loaded up for the festival",
    "focus": "attention",
    "width": 1600,
    "height": 1200,
    "widths": [
      480,
      800,
      1200,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoUAA8APwlurk+rpiQiMAgBcCEJYgCABK/4D0PcP5z4m28rIAD+6ydaFHrD5NV5+tcg427AQq2536r7+9HXdWV46+3w45w2EcRc7+sn/6uiOfmQqFApvivbQwPfx12gmIYxKpP8b+7rmuYnvoaqcAAA"
  },
  {
    "slug": "kitchen-garden",
    "cat": "community",
    "alt": "Vegetable beds framed in timber and planted in old tyres, green with onions and kale",
    "caption": "The kitchen garden",
    "focus": "attention",
    "width": 1280,
    "height": 960,
    "widths": [
      480,
      800,
      1200,
      1280
    ],
    "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwAwCdASoUAA8APwlurk+rpiQiMAgBcCEJaABTAAdG2+Ykxp7AyEOAAMs39tM4rLDnfYhjIZl7SSzYJUXv5x6qs2qkr5JRvA+Gg3qrzFX7lM/RfUaOxN2WOzjg0ic+vXJeIMzdGQndJg8DgL52L1kHWs4RsGNMD2CvMbG8Ze/le4+lx5DKTavD4CC7U+4UAAA="
  },
  {
    "slug": "agriculture-lesson",
    "cat": "community",
    "alt": "A learner reading from his notes to a class standing among the vegetable beds",
    "caption": "Agriculture, taught in the beds themselves",
    "focus": "attention",
    "width": 1280,
    "height": 960,
    "widths": [
      480,
      800,
      1200,
      1280
    ],
    "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABwBACdASoUAA8APwlur0+rpiQiMAgBcCEJZACsEf/gQHyWjSNgRLa0/4y0AAD7fmryyKsaRhVwLfgpMX9mKb/uJUuK2XgOQ4jZEf6ASEaLX3fJ1k+3ggABLMzsf0rc1xxT8BImqhz7NUuwJK+ujQrItgHLp6MEQTFaimrDQUvswtmavC1AxV0AAAA="
  },
  {
    "slug": "kisumu-airport",
    "cat": "trips",
    "alt": "The school group photographed under the Kisumu International Airport sign",
    "caption": "Kisumu International Airport",
    "focus": "attention",
    "width": 1040,
    "height": 780,
    "widths": [
      480,
      800,
      1040
    ],
    "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQAwCdASoUAA8APwlur0+rpiQiMAgBcCEJZACdACKk6ydWuFhVeQAA/Ej8Mfi4PhQM23NBJFX6bZGd+mwZ1xz+zvLeQpy0RymlK8j8epv3fZYawGebeuMkOgsBQHBMyAAGBUc0tz3yxBwACi3l5UVFIMJiL+DovYAAAA=="
  },
  {
    "slug": "airport-group",
    "cat": "trips",
    "alt": "Learners and their teachers outside the airport terminal on the school trip",
    "caption": "First time at an airport",
    "focus": "attention",
    "width": 1040,
    "height": 780,
    "widths": [
      480,
      800,
      1040
    ],
    "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABQBACdASoUAA8APwlur0+rpiQiMAgBcCEJZgCdIKnDFjaq78+P22KoEcWAAP3MYWBtPlZmcMmAgvp0szB7xDCCWO0WVPC4e7aoXDZ4F87xqw2MU3IKNy2I3DUR2gEkQjEObbdB+7EMqMeXglVXQbR8FoH5kD4wU7tYoaPFcAA="
  },
  {
    "slug": "school-gate-trip",
    "cat": "trips",
    "alt": "The whole party seated and standing at the gate of the place they were visiting",
    "caption": "Everyone who travelled",
    "focus": "attention",
    "width": 1040,
    "height": 780,
    "widths": [
      480,
      800,
      1040
    ],
    "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACQAwCdASoUAA8APwlurk+rpiQiMAgBcCEJZQDE2A0301CqXrUQAP4Ak7CZ4Jyv/pZOVjBg7pePizTqwp2tmGzT931NWRuvM6+fT6jfDAU0xb1JH2INPLvR9aU09CeGQMJPvUUdYHiU5tAA"
  },
  {
    "slug": "motto-wall",
    "cat": "campus",
    "alt": "Learners and a teacher standing under the painted wall reading The School Motto: Ora et Labora, Pray and Work",
    "caption": "Ora et Labora, painted on the wall",
    "focus": "attention",
    "width": 1280,
    "height": 960,
    "widths": [
      480,
      800,
      1200,
      1280
    ],
    "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADQAwCdASoUAA8APwlur0+rpiQiMAgBcCEJQBOkCYgp7FbhO6QoDt4A/e7dxDv/S2BRMaIgrYLqubKEw+sXBYPwh2BqgaBRbGG5OXx1xznlBS+vFzKnFSlh6lt46FnLAb7orSXUaZXnVtu0Hgjlma0o3CQ0HZO+ucnsmMhDxNWzeAAA"
  },
  {
    "slug": "office-desk",
    "cat": "campus",
    "alt": "A member of staff going through papers at a desk with two learners, the wall behind painted Brothers of St Charles Lwanga",
    "caption": "The office",
    "focus": "attention",
    "width": 960,
    "height": 1280,
    "widths": [
      480,
      800,
      960
    ],
    "blur": "data:image/webp;base64,UklGRv4AAABXRUJQVlA4IPIAAAAwBgCdASoUABsAPwlyr0+rpyQiMAgBcCEJbAC2+ySnSnjFtAt6EYS0mtxM6HQMNO2vSkGG4VrNtnyYAP7iXhJzr+ORluq17YIKBFNPoZmSu1S/QiIwyMvmFBfLTAGU2ZJaavJ5jzpZtmwPtNWkEQe44KDWLGd1fls2vzG3N5cHI6d5bU8D3Wairbver3EiGtHlAIj8GjntFCj1ZoJmwbzuUt4t3f9gpJ/aIMJ9fP12bKwiNGS+CDluFyHanPOYqrSCH6kLJbaOOFQ3tR7sZQdx5W9ZKNQowFeg7g5TT/P/nLkIznyxlmU6yQwsqV2+QDAAAA=="
  },
  {
    "slug": "one-to-one",
    "cat": "life",
    "alt": "A teacher going through a learner's work with him at a table under the trees",
    "caption": "One to one, under the trees",
    "focus": "attention",
    "width": 960,
    "height": 1280,
    "widths": [
      480,
      800,
      960
    ],
    "blur": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAAAQBgCdASoUABsAPwl2r1Grp6QisBgIAXAhCWoAv2rqL/43gXDkZ8aTDYy29z1IoLWcUA8PgnUeVdAA84gFJlsO/4WqJfbY/Vt4SBwxfFIP08jSngFXq4jgIvz5oje92cGJMLfN7KwzrOROK6pjGKqHMrfHd7aIHGOsv7QUQj7xcaKV8iEtab4knRwpb9hiOoSVwVLvK17TU4aOjewZNAeRUJoJ6CjO+cxiFMwmeSRzHGsgyxk8O6d0T2LdpjLeOGvZf3vwdquypVr4AAA="
  }
];

const bySlug = new Map(photos.map((p) => [p.slug, p]));

/** Look a photo up by slug. Throws at build time if the slug is wrong, so a
 *  typo in a page never ships as a silently missing image. */
export function photo(slug: string): Photo {
  const found = bySlug.get(slug);
  if (!found) throw new Error(`Unknown photo "${slug}"`);
  return found;
}

export function photosIn(cat: PhotoCategory): Photo[] {
  return photos.filter((p) => p.cat === cat);
}
