import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { can, requirePermission } from "@/lib/rbac";
import { formatMoney } from "@/lib/money";
import { deleteDraftRun, markPayrollPaid } from "@/lib/actions/payroll-actions";
import { PrintButton } from "@/components/fees-forms";

export const metadata: Metadata = { title: "Payroll Run" };

export default async function PayrollRunPage({
  params,
}: {
  params: Promise<{ runId: string }>;
}) {
  const user = await requirePermission("payroll", "view");
  const { runId } = await params;

  const [run, mayEdit, mayArchive] = await Promise.all([
    db.payrollRun.findUnique({
      where: { id: runId },
      include: {
        items: { include: { staff: true }, orderBy: { staff: { employeeNo: "asc" } } },
      },
    }),
    can(user.role, "payroll", "edit"),
    can(user.role, "payroll", "archive"),
  ]);
  if (!run) notFound();

  const totals = run.items.reduce(
    (t, i) => ({
      basic: t.basic + i.basicCents,
      allowances: t.allowances + i.allowancesCents,
      deductions: t.deductions + i.nssfCents + i.shifCents + i.payeCents + i.otherDeductCents,
      gross: t.gross + i.grossCents,
      net: t.net + i.netCents,
    }),
    { basic: 0, allowances: 0, deductions: 0, gross: 0, net: 0 },
  );

  return (
    <div className="mx-auto max-w-5xl space-y-6">
      <div className="flex flex-wrap items-end justify-between gap-4 print:hidden">
        <div>
          <p className="text-xs font-bold uppercase tracking-[0.14em] text-ink-400">
            <Link href="/payroll" className="hover:text-brand-600">Payroll</Link>
          </p>
          <h1 className="font-display text-2xl font-extrabold text-ink-900">
            Payroll register — {run.month}
            {run.status === "PAID" ? (
              <span className="chip ml-3 bg-leaf-500/10 align-middle text-leaf-600">
                Paid{run.paidBy ? ` by ${run.paidBy}` : ""}
              </span>
            ) : (
              <span className="chip ml-3 bg-sun-400/15 align-middle text-sun-500">Draft</span>
            )}
          </h1>
          <p className="mt-1 text-sm">
            {run.items.length} staff · gross {formatMoney(totals.gross)} · net{" "}
            {formatMoney(totals.net)} · generated by {run.generatedBy}.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <PrintButton label="Print register" />
          {run.status === "DRAFT" && mayEdit && (
            <form action={markPayrollPaid}>
              <input type="hidden" name="id" value={run.id} />
              <button type="submit" className="btn btn-primary !py-2 text-xs">
                Mark as paid → post to expenses
              </button>
            </form>
          )}
          {run.status === "DRAFT" && mayArchive && (
            <form action={deleteDraftRun}>
              <input type="hidden" name="id" value={run.id} />
              <button type="submit" className="btn btn-danger !py-2 text-xs">
                Delete draft
              </button>
            </form>
          )}
        </div>
      </div>

      <div className="card overflow-x-auto">
        <table className="table-admin">
          <thead>
            <tr>
              <th>Staff</th>
              <th className="text-right">Basic</th>
              <th className="text-right">Allowances</th>
              <th className="text-right">NSSF</th>
              <th className="text-right">SHIF</th>
              <th className="text-right">PAYE</th>
              <th className="text-right">Other</th>
              <th className="text-right">Net pay</th>
              <th className="text-right print:hidden">Payslip</th>
            </tr>
          </thead>
          <tbody>
            {run.items.map((i) => (
              <tr key={i.id}>
                <td className="font-semibold text-ink-900">
                  {i.staff.lastName}, {i.staff.firstName}
                  <span className="ml-2 font-mono text-xs font-normal text-ink-400">
                    {i.staff.employeeNo}
                  </span>
                </td>
                <td className="text-right">{formatMoney(i.basicCents)}</td>
                <td className="text-right">{formatMoney(i.allowancesCents)}</td>
                <td className="text-right text-danger-500">{formatMoney(i.nssfCents)}</td>
                <td className="text-right text-danger-500">{formatMoney(i.shifCents)}</td>
                <td className="text-right text-danger-500">{formatMoney(i.payeCents)}</td>
                <td className="text-right text-danger-500">{formatMoney(i.otherDeductCents)}</td>
                <td className="text-right font-bold text-leaf-600">{formatMoney(i.netCents)}</td>
                <td className="text-right print:hidden">
                  <Link
                    href={`/payroll/${run.id}/slip/${i.id}`}
                    className="text-xs font-bold text-brand-600 hover:text-brand-700"
                  >
                    Payslip →
                  </Link>
                </td>
              </tr>
            ))}
            <tr className="font-bold">
              <td className="text-ink-900">Totals</td>
              <td className="text-right">{formatMoney(totals.basic)}</td>
              <td className="text-right">{formatMoney(totals.allowances)}</td>
              <td colSpan={3} />
              <td className="text-right text-danger-500">{formatMoney(totals.deductions)}</td>
              <td className="text-right text-leaf-600">{formatMoney(totals.net)}</td>
              <td className="print:hidden" />
            </tr>
          </tbody>
        </table>
      </div>

      {run.status === "DRAFT" && (
        <p className="text-xs text-ink-400 print:hidden">
          Marking as paid locks the run and posts the gross total (
          {formatMoney(totals.gross)}) to Income &amp; Expenses under Salaries &amp; Wages.
        </p>
      )}
    </div>
  );
}
